### PR TITLE
DM-55 Add GPU powered MATLAB Dockerfile

### PR DESCRIPTION
**Pull request by aranega**
This PR adds a Dockerfile for MATLAB targeting GPU architectures (CUDA 11.8), and with the last `tenserflow` with GPU enabled capability installed.

The PR also adds a new entry in the `config.yaml.j2` to run the image associated to the MATLAB GPU Dockerfile.

This image builds and runs fine in the tests we made in our clusters with GPUs. However, due to the configuration of our clusters, the `LD_LIBRARY_PATH` variable needed to be updated. This is done in the `Dockerfile`, but commented as it was depending on our cluster config. This might need to be adjusted depending on the GPU server config in dandi-hub. 

gpu1

### CODE REVIEW

**Comment by vijayiyer05** [comment]
FYI @satra, this PR pertains to the GPU+MATLAB new container option determined at our August meeting last year

**Comment by satra** [comment]
@aranega - please merge with current master and update the config profile to match the other GPU profile.

**Comment by aranega** [comment]
@satra Done! Thanks for the review and the advice.

**Comment by satra** [comment]
i'll merge this in, but it will still require a few steps before we can enable it. first i need to make sure docker builds the images.

**Comment by vijayiyer05** [comment]
> i'll merge this in, but it will still require a few steps before we can enable it. first i need to make sure docker builds the images.
Thank you for explaining this interim status @satra .
Should any issues/questions arise w/ the Docker build, don't hesitate to let us know, here or otherwise.

**Comment by satra** [comment]
this is done, but i haven't tested anything. so please let us know if it works.

**Comment by aranega** [comment]
@satra @vijayiyer05 I made a test and the GPU is well discovered by python/tensorflow and by MATLAB 

gpu2
gpu1

**Pull request merged**
