### PR TITLE
Add hdf5 extension

### PR DESCRIPTION
**Pull request by satra**
the extension needs to be upgraded to support  jupyterlab 3.0 before this PR can be merged.

### CODE REVIEW

**Comment by yarikoptic** [comment]
is this still needed? I thought that HDF5 ROS3 support is now "native" so likely no further actions like this needed?

**Comment by kabilar** [comment]
Hi @satra, do you think this fix still needs to be integrated into the codebase? Thank you.

**Comment by satra** [comment]
should be replaced by this: https://github.com/silx-kit/jupyterlab-h5web

**Comment by satra** [comment]
but in general this should be part of the do_eks update in terms of images.

**Comment by kabilar** [comment]
Thank you.  I have created a new issue to track (#122) and we will include this feature as part of the ongoing refactor.

**Pull request closed without merging**
