### PR TITLE
[WIP] adding fakeroot and iptables to test singularity compose

### PR DESCRIPTION
**Pull request by djarecka**
@asmacdo - this is the last version I was testing last week

### CODE REVIEW

**Comment by kabilar** [comment]
Hi @djarecka, also following up on these changes.  Should we explore further and possibly integrate into the codebase?  Thank you.

**Comment by djarecka** [comment]
@asmacdo - you worked later more on the hub, do you have opinion if this should be included?

**Comment by asmacdo** [comment]
I think let's close for now. If users ask for this feature we can come back to it.

**Comment by kabilar** [comment]
Thanks team.  Will close based on the above discussion.

**Pull request closed without merging**
