### PR TITLE
Create GitHub Actions workflows to build and push Docker Images

### LINKED ISSUE #141: Review (and possibly update) the automated Docker image build and publishing processes
## Requirements
- [ ] Document the current automated process for building the Docker images and publishing to Docker Hub
  1. From what I understand about the CI, the following occurs in Docker cloud upon merging of a pull request:
      1. Receives a trigger
      2. Rebuilds the images
      3. Pushes the images to Docker Hub.
  2. We should clarify with Satra and get access to this vendor.
- [ ] Evaluate alternative solutions
  1. It might be more transparent and easier to add additional Dockerfiles if we integrate the image build process into GitHub Actions but I am not sure of the tradeoffs.

### PR DESCRIPTION
**Pull request by kabilar**
Fix #141 

- [x] Add GitHub Actions workflow to test the image builds upon pull request
- [x] Add GitHub Actions workflow to build and push to Docker Hub upon merge to `main`
  - [x] Use existing `DOCKERHUB_TOKEN` and `DOCKERHUB_USERNAME` GitHub Actions secrets
  - [x] Rename `Dockerfile` tag from `latest` to `latest-base`
  - [x] Confirm that the images build on my fork and push to my Docker Hub.  See successful [GitHub Actions run](https://github.com/kabilar/dandi-hub/actions/runs/12283103882) and [Docker Hub](https://hub.docker.com/r/kabilar/dandihub/tags).
- [x] Disable `Build configuration` on Docker Hub since we will now be pushing from GitHub

cc @satra

### CODE REVIEW

**Review by satra — APPROVED** [review]
overall looks good to me. it may be good to see if the build caches so that we don't rebuild all each time this workflow is run.

**Comment by asmacdo** [comment]
LGTM

I don't think it will do any build caching since it will fire up a totally fresh instance each push. That shouldn't be a problem for dockerhub if the builds are deterministic, but it probably will waste some power.  


IIUC these images don't actually make use of anything in the repo other than the Dockerfiles themselves, so maybe?

```
on:
  push:
    paths:
      - 'Dockerfile.*`
```
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-paths

**Comment by kabilar** [comment]
> overall looks good to me. it may be good to see if the build caches so that we don't rebuild all each time this workflow is run.

Good idea.  I was able to add a caching mechanism.  For reference, here are the docs:

- https://docs.docker.com/build/cache/backends/inline/
- https://docs.docker.com/build/ci/github-actions/cache/

**Comment by kabilar** [comment]
> IIUC these images don't actually make use of anything in the repo other than the Dockerfiles themselves, so maybe something like...

Good idea.  I have added the `paths` filter to both workflows.

**Comment by kabilar** [comment]
Hi @asmacdo, did you set an expiration date on Docker Hub for the `DOCKERHUB_TOKEN` secret?  I was able to successfully run the `Build Docker Images` workflow but the `Build and Push Docker Images` failed with the following error ([link](https://github.com/dandi/dandi-hub/actions/runs/12303383445/job/34338365874#step:6:13622)):

```
#19 ERROR: failed to push ***/dandihub:latest-matlab: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3A***%2Fdandihub%3Apull%2Cpush&service=registry.docker.io: 401 Unauthorized
```

If the token is expired, I can replace the current one.  Thanks.

**Comment by asmacdo** [comment]
@kabilar I used a repo specific key, you'll need a new one.

**Comment by kabilar** [comment]
Thanks @asmacdo.

All images have been built and pushed to Docker Hub.  See [latest GA run](https://github.com/dandi/dandi-hub/actions/runs/12304403780) and images on [Docker Hub](https://hub.docker.com/r/dandiarchive/dandihub/tags).

cc @satra

**Comment by satra** [comment]
@kabilar - thank you. as part of this should we disable autobuilds on dockerhub?

**Comment by kabilar** [comment]
Hi @satra, I disabled the autobuilds on dockerhub.

I have noticed an issue with the GA builds.  Only the `images/Dockerfile` is being built for all entries in [matrix strategy](https://github.com/dandi/dandi-hub/blob/b3065528239ac0f81328822b03abe6a3202ff784/.github/workflows/docker-push.yaml#L15-L25).  Trying to resolve now.

**Pull request merged**
